apiVersion: v1
kind: Pod
metadata:
  name: haproxy
spec:
  containers:
    - name: haproxy
      image: haproxy
      volumeMounts:
        - mountPath: /usr/local/etc/haproxy/
          name: config
  volumes:
    - name: config
      configMap:
        name: haproxy
    
